### ISSUE TITLE
[Enhancement] Reusing trained model for other sports?

### ISSUE THREAD

**Issue by timtensor** [roboflow-ai/notebooks#12]
Hi first of all thanks for such a good notebook and a follow along youtube tutorial. 
I was thinking of the possibility to reuse the model for smaller sports like doubles tennis etc.  

1.  So four players + tennis ball. If i understand correctly the pre trained mode , from the Yolo V5 model should detect the ball . But perhaps the tracking is lost. 
2. How can i get the x,y co-ordinates of the ball and also the players in action. The idea would be to draw the movement of the ball, players over a 2D plane , shown in the image below 
3. For visual purposes , how can one modify the implementation
![image](https://user-images.githubusercontent.com/49288450/206515133-b1c5bad1-eb5d-4698-9366-525fe84d2551.png)
 to have a set of trail spots basically for the visualization process.

**Comment by timtensor** [comment]
Stationary , facing the players.

**Comment by timtensor** [comment]
Thanks, i though first just outputting the x,y value of the objects. so the displacement would be x pixels, y pixel. If i know the ball is round 4 or 5 pixel i plan to convert pixel into meters. Perhaps it is not the best way. 

So can i just use the pretrained model to run it on a video (tennis or volley) and check for the outputs. I think for that I would not need the kaggle and bundesliga datasets as they are specifically used for football?

**Comment by SkalskiP** [comment]
> So can i just use the pretrained model to run it on a video (tennis or volley) and check for the outputs. I think for that I would not need the kaggle and bundesliga datasets as they are specifically used for football?

Yup lets start with model pre-trained on COCO dataset, to have some baseline.

> Thanks, i though first just outputting the x,y value of the objects. so the displacement would be x pixels, y pixel. If i know the ball is round 4 or 5 pixel i plan to convert pixel into meters. 

What I usually do is I measure size of real life object in m or cm, and I use those dimensions like in example I showed you.

**Comment by SkalskiP** [comment]
@timtensor can I close the issue?

**Comment by SkalskiP** [comment]
I'm closing the issue for now. Feel free to reopen if you'll have more questions.
