### ISSUE TITLE
PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by felri** [roboflow-ai/notebooks#18]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

[how-to-track-football-players.ipynb](https://github.com/roboflow-ai/notebooks/blob/main/notebooks/how-to-track-football-players.ipynb)

### Bug

I'm trying to run the model [best.pt located here](https://docs.google.com/uc?export=download&id=1OYwrlRti4cieuvVr8ERaJhTQdFJXWT4I) using the following command:

```
%cd {HOME}/yolov5
!python detect.py --weights best.pt --img 1280 720 --conf 0.25 --source {HOME}/clipcut.mp4 --name custom

/content/yolov5
detect: weights=['best.pt'], source=/content/clipcut.mp4, data=data/coco128.yaml, imgsz=[1280, 720], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=custom, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5 🚀 v7.0-30-g342fe05 Python-3.8.16 torch-1.13.0+cu116 CUDA:0 (Tesla T4, 15110MiB)

Traceback (most recent call last):
  File "detect.py", line 261, in <module>
    main(opt)
  File "detect.py", line 256, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 98, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
  File "/content/yolov5/models/common.py", line 345, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
  File "/content/yolov5/models/experimental.py", line 79, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

using the yolo5x.pt that comes in the yolo repo works fine: 

`!python detect.py --weights yolov5x.pt --img 1280 720 --conf 0.25 --source {HOME}/clipcut.mp4 --name coco`

### Environment

google colab

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @felri 👋🏻! Thanks from moving from Reddit to GitHub. Quick question to start. Do you run our colab without any changes? Is it possible that you'd share with us `clipcut.mp4` file?

**Comment by felri** [comment]
I made [a copy of the changes I did in the notebook](https://colab.research.google.com/drive/1Ra7O07-ubIaXM2-GR8pTrmJYANfgtXsB#scrollTo=tV9XIIPnI4GV), I don't think I've changed anything important. Thanks for the help!

https://user-images.githubusercontent.com/56592364/206935437-5961c5aa-c13c-4f23-84c3-77e6ca3dcae4.mp4

**Comment by felri** [comment]
@SkalskiP oh my god that was so obvious, I'm sorry for using your time for such a dumb error hehe, I'm able to run your model and it's way better than the base yolo5x.

By the way do you think bytetrack will solve the tracks being lost on some frames or it would be better to fine tune your model with data more similar to my clip? (more of a bird eye view)


https://user-images.githubusercontent.com/56592364/207025041-142596d0-ffff-4800-8f2d-1bbb970c8f9f.mp4
